Vanilla set up
ubuntudesign/maas-gui-vanilla-theme pull request #11
Opened 2016-10-11 16:27 UTC by richmccartney

#### What's this PR do?

Updates:

- Package.json to use the new dev dependancies based off vanilla framework v1.0
- Updates .gitignore to follow the same content as vanilla framework v1.0
- Adds vanilla framework v1.0 as a dependancy 
- Removes install_dependancies.sh
- Updates .scss-lint.yml
- Adds required gulp js files
- Adds updated run file

#### Where should the reviewer start?

Pull the branch down and run ```npm i```

#### How should this be manually tested?

Run ```gulp test``` and it should use the new tools from vanilla framework v1

#### Any background context you want to provide?

_n/a_

#### What are the relevant tickets?

#8 

#### Screenshots (if appropriate)

_n/a_

#### Questions:

_n/a_

2016-10-11 17:48 UTC, anthonydillon requested changes
Thanks @richmccartney some comments inline.

2016-10-11 17:48 UTC, anthonydillon commented on gulpfile.js
> +wrench.readdirSyncRecursive('./gulp').filter(function(file) {
So we need this as we have no js in the theme?

2016-10-11 17:48 UTC, anthonydillon commented on CONTRIBUTING.md
> +So, you'd like to contribute to the Vanilla Dashboard Theme? Great!
It should be `Dashboard Vanilla Theme`.

2016-10-11 17:48 UTC, anthonydillon commented on CONTRIBUTING.md
> +We use the [Issues tracker](https://github.com/ubuntudesign/vanilla-dashboard-theme/issues) to track all our bugs and feature requests, collectively known as 'issues'.
The github report should be `dashboard-vanilla-theme`

2016-10-11 17:48 UTC, anthonydillon commented on package.json
> +  "name": "maas-gui-vanilla-theme",
This should be dashboard-vanilla-theme.

2016-10-11 17:48 UTC, anthonydillon commented on package.json
> +  "homepage": "https://github.com/ubuntudesign/maas-gui-vanilla-theme#readme"
This package.json has two homepage values.

2016-10-11 20:24 UTC, richmccartney commented on gulpfile.js
> +wrench.readdirSyncRecursive('./gulp').filter(function(file) {
I can see this theme having JS in the future. Especially if there are react / angular components from the respective products. For the time being I will remove this.

2016-10-11 20:29 UTC, richmccartney commented
@anthonydillon if you can give this a second review, the package.json changes wont work until the theme name has change.

2016-10-11 20:46 UTC, anthonydillon approved these changes
Awesome, thanks :+1:

2016-10-12 14:12 UTC, anthonydillon commented
Can you please change naming back to `maas-gui-vanilla-theme`

2016-10-18 15:51 UTC, merged