Removing all dashboard references
ubuntudesign/maas-gui-vanilla-theme pull request #47
Opened 2016-10-18 16:10 UTC by richmccartney

#### What's this PR do?

Removes all remaining references to dashboard in the develop branch

#### Where should the reviewer start?

Pull the branch and check all documentation doesn't have references to dashboard

2016-10-18 16:21 UTC, anthonydillon requested changes
The titles of both the `CONTRIBUTING.md` and `README.md` still have the new name.

2016-10-19 16:45 UTC, richmccartney commented on CONTRIBUTING.md
Can you confirm this is fine now?

2016-10-19 16:46 UTC, richmccartney commented
@anthonydillon can you confirm this is fine now?

2016-10-19 20:42 UTC, anthonydillon commented
No the issue above still exists.

2016-10-20 08:43 UTC, richmccartney commented on CONTRIBUTING.md
> +When [submitting a new issue](https://github.com/ubuntudesign/maas-gui-vanilla-theme/issues/new), please check that it hasn't already been raised by someone else. We've provided a template for new is
@anthonydillon can you not see these changes at all in the files?

2016-10-20 08:43 UTC, richmccartney commented on README.md
> +To see the latest changes and updates live please view the [demo page](http://ubuntudesign.github.io/maas-gui-vanilla-theme/)
@anthonydillon same with this change?

2016-10-20 08:45 UTC, anthonydillon commented
Yea I can see them but I'm referring to the title.
# Contributing to Dashboard Vanilla Theme

2016-10-20 08:59 UTC, anthonydillon commented
Now it is just the title of the Readme.
# Dashboard Vanilla Theme

2016-10-21 11:40 UTC, anthonydillon approved these changes

2016-10-21 11:42 UTC, anthonydillon commented
Looks good.

2016-10-21 13:50 UTC, merged