Applying new mobile styles to the secondary navigation
ubuntudesign/maas-gui-vanilla-theme pull request #71
Opened 2017-06-15 14:44 UTC by richmccartney

#### What's this PR do?

Applies the new secondary navigation design which can be found here https://github.com/CanonicalLtd/MAAS-design/blob/master/Mobile%20navigation/Flat_Visuals/Mobile-secondary-nav.png

#### Where should the reviewer start?

- Pull down the branch and run ```npm i``` and then ```gulp build```

#### How should this be manually tested?

- Open ```demo/index.html``` and test the secondary navigation in mobile view. The content should overflow scroll at ```768px``` breakpoint.

2017-06-15 15:17 UTC, anthonydillon requested changes
Small comment in sass and is this pattern missing the active styling?

2017-06-15 15:17 UTC, anthonydillon commented on scss/_patterns.page-navigation.scss
> +        background: linear-gradient(90deg,hsla(0,0%,100%,0) 0,#fff);
please use `$white` and add spaces after commas.

2017-06-15 15:19 UTC, anthonydillon commented
The `overflow: scroll` results in a large scrollbar in Chrome/Ubuntu:
![maas gui - pattern library](https://user-images.githubusercontent.com/1413534/27188538-56c82298-51e6-11e7-91f9-c78eec0165b4.png)

2017-06-16 09:15 UTC, richmccartney commented
@anthonydillon if you can pull this down and give it another look :)

2017-06-16 15:40 UTC, anthonydillon approved these changes
:+1:

2017-06-16 15:41 UTC, merged